### ISSUE TITLE
My game crashed while loading this mod.

### ISSUE THREAD

**Issue by lava191810** [theendercore/BlockBeams#1]
If the mod is not loaded, it will run normally and crash after loading.
[latest.log](https://github.com/theendercore/BlockBeams/files/13327032/latest.log)
[crash-2023-11-12_10.54.56-client.txt](https://github.com/theendercore/BlockBeams/files/13327035/crash-2023-11-12_10.54.56-client.txt)

**Comment by theendercore** [comment]
Okay so...

Nr. 1 Looks just like a weird Kotlin bug, have see this before no idea why its happening here and now. (Last time I test it it worked fine)
But that's not that bad ill get a fix out in like 10 min.

Nr. 2 When ever you post logs or crash reoprts you should put then thru something like https://mclo.gs/ so you don't dox your self 

Nr. 3 You **_SHOULD NOT_** use optifine its old and not as good as it was back in the day plus there are faster alternatives [Link - https://fabricmc.net/wiki/community:optifine_alternatives]

**Comment by theendercore** [comment]
Okay mod is now public on Modrinth and should soon be on cf as well. I will presume this issue is fixed for now.
